# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.7.1' # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@2.1.2
                - '@prettier/plugin-xml@0.12.0'
            types_or: [ts, javascript, json]
            args: [--config, .prettierrc.json]
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v8.18.0' # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint
                - '@typescript-eslint/parser@5.8.0'
                - '@typescript-eslint/eslint-plugin@5.8.0'
            files: \.[jt]sx?$
            args: [-c, .eslintrc]
            types: [file]
    - repo: local
      hooks:
          - id: 'compiling...'
            name: 'building...'
            language: node
            args: [-p, tsconfig.json, --outDir, dist]
            entry: tsc
            pass_filenames: false
            stages: [commit, push]
